version = 1
SPDX-PackageName = "invoke-plugin-for-sphinx"
SPDX-PackageSupplier = "kai.mueller01@sap.com"
SPDX-PackageDownloadLocation = "https://github.com/SAP/invoke-plugin-for-sphinx"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 SAP SE or an SAP affiliate company and invoke-plugin-for-sphinx contributors"
SPDX-License-Identifier = "Apache-2.0"
