name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install project
        run: pip install -e .[dev,test]
      - name: run pre-commit
        run: "pre-commit run --all"
  ci-test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        sphinx-version: ["7.0.*", "7.*", "8.0.*"]
        invoke-version: ["2.1.*", "2.*"]
        exclude:
          # sphinx 8 does not support python 3.8
          - sphinx-version: "8.0.*"
            python-version: "3.8"
          # sphinx 8 does not support python 3.9
          - sphinx-version: "8.0.*"
            python-version: "3.9"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project
        run: pip install -e .[test]
      - name: "Install sphinx"
        run: "pip install -U sphinx==${{ matrix.sphinx-version }} invoke==${{ matrix.invoke-version }}"
      - name: run tests (with coverage)
        run: "pytest --cov invoke_plugin_for_sphinx --cov-report html --cov-report xml tests/"
      - name: run diff-cover
        run: "diff-cover --config-file pyproject.toml coverage.xml"
